In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

## Making list of all review URLs

In [2]:
base = "https://www.gsmarena.com/apple_iphone_xs-reviews-9318p"
end = ".php"
url_list = []
for i in range(1,20):
    url_list.append(base+str(i)+end)
    
print(url_list)

['https://www.gsmarena.com/apple_iphone_xs-reviews-9318p1.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p2.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p3.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p4.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p5.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p6.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p7.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p8.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p9.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p10.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p11.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p12.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p13.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p14.php', 'https://www.gsmarena.com/apple_iphone_xs-reviews-9318p15.php', 'https://www.gsmarena.com/apple_iphone_xs-review

## Function to flatten nested list

In [3]:
flatten = lambda l: [item for sublist in l for item in sublist]

## Applying operations to each URL

In [42]:
all_review = [] ## List to store all the reviews

for url in url_list:
    print(url)
    page=requests.get(url)  ## Retrieve HTML page
    soup = BeautifulSoup(page.content,'html.parser')  ## Parse it by beautiful soup
    review = soup.find_all('p', class_='uopin')
    documents = [x.text.strip().split(".") for x in review] ## List of review on that page
    all_review.extend(documents)

https://www.gsmarena.com/apple_iphone_xs-reviews-9318p1.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p2.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p3.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p4.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p5.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p6.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p7.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p8.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p9.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p10.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p11.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p12.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p13.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p14.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p15.php
https://www.gsmarena.com/apple_iphone_xs-reviews-9318p16.php
https://www.gsmarena.com/apple_ip

In [51]:
[x.text.strip().split(".") for x in review]

[['Except a thing or two, there is absolutely NO difference between this and iphone X',
  '  \r\nHave they given wrong specs or what?'],
 ['Anonymous, 12 Sep 2018From IP67 to IP68 ',
  '',
  ' what a big difference XDwatch this space'],
 ['Chris-the-Apple-boy, 12 Sep 2018This is the initial version of the page, expect updates within 2 hoursOk'],
 ['Which model gets dual physical sim??? XS or XS Max???'],
 ['Galaxy S6 under iPhone skin',
  '',
  '',
  ' \r\nSame specs, same functions, nothing new',
  '',
  '',
  '\n \r\nOh yeah, monster Apple homebrew cpu :D'],
 ['its literally took Apple more than 4 years to put dual SIM, but another 10 years for Micro SD hahahah'],
 ['One thing is for certain',
  '',
  '',
  " there's ZERO reason for iPhone X users to upgrade to Xs",
  ' This phone is literally the same thing with upgraded SoC & RAM only!'],
 ['Nothing too exciting!'],
 ['From IP67 to IP68 ', '', ' what a big difference XD'],
 ["I'm early to this!!!"],
 ['ddavid, 12 Sep 20182716mah ? 

In [52]:
all_reviews_flat = flatten(all_review)

all_reviews_flat = [x for x in all_reviews_flat if len(x)>20]

In [53]:
len(all_reviews_flat)

1199

In [55]:
all_reviews_flat[:10]

['Fer, 24 Apr 2019This evaluation aims to examine how the iPhone XS is believed to be the best iPhone so far',
 ' moreThen came along S10',
 'Fer, 24 Apr 2019This evaluation aims to examine how the iPhone XS is believed to be the best iPhone so far',
 ' moreThe iPhone XS is the worst of the new iPhones \r\nThe XR is more fair valued with a great camera \r\nThe XS is literraly the same as the X ($760) \r\nAnd the XS MAX has a big screen better battery better camera \r\nTHE XS IS THE WORST!!!!!!!!!1',
 'This evaluation aims to examine how the iPhone XS is believed to be the best iPhone so far',
 ' I have stated some evidence of the success of the iPhone XS and its sales',
 ' \n \r\nPeople around the world snapped up the iPhone XS models more quickly than they did the iPhone 8 series last year',
 '46 million iPhone XS models in the first week',
 ' “The report claims that the new iPhones have generated 7% more revenue during its first week sales, compared to the combined sales of last yea

In [60]:
#copy_allpage_mobile_review = pd.DataFrame({"Reviews":all_reviews_flat})
#copy_allpage_mobile_review.to_csv("copy_allpage_mobile_review.csv",index=False)

In [61]:
#pd.set_option('display.max_colWidth',-1)
#copy_allpage_mobile_review.head()

Reviews
0  Fer, 24 Apr 2019This evaluation aims to examine how the iPhone XS is believed to be the best iPhone so far                                                                                                                                               
1   moreThen came along S10                                                                                                                                                                                                                                 
2  Fer, 24 Apr 2019This evaluation aims to examine how the iPhone XS is believed to be the best iPhone so far                                                                                                                                               
3   moreThe iPhone XS is the worst of the new iPhones \r\nThe XR is more fair valued with a great camera \r\nThe XS is literraly the same as the X ($760) \r\nAnd the XS MAX has a big screen better battery better camera \r\nTHE XS IS THE WORST!!!!!!!!!1
4  This evaluation aims to examine how the iPhone XS is believed to be the best iPhone so far

In [62]:
len(copy_allpage_mobile_review)

1199

In [209]:
mobrev = pd.read_excel('newcopy_mobile_review.xlsx')

In [210]:
len(mobrev)

1254

In [211]:
mobrev.shape

(1254, 2)

In [212]:
mobrev.tail()

sentiment  \
1249  POS        
1250  NEG        
1251  NEG        
1252  NEG        
1253  NEG        

                                                                                                                                                                                      Reviews  
1249    Apple is 3 years behind Samsung and Huawei                                                                                                                                             
1250  IMO,why apple a bit fail in china: \r\r\nskyhigh price, big side bezel and big notch, no FM radio and headphone jack, small battery for the size, heavy weight for the size              
1251  Shaun, 22 Mar 2019How about you don't?\r\r\nI've moved from iOS to Android, got the S10e now, no regrets                                                                                 
1252   moreCommon! How did you say Iphones SE, 7, 8 were rubbish?                                                                                                                              
1253  I wish camscanner and many apps running better on S10, i dont think twice, but so many apps that i use, running better on ios, and it will not change may be until in the next 10 years

In [213]:
sum(mobrev['sentiment'] == " ")

0

In [214]:
mobrev['sentiment'] = mobrev['sentiment'].astype('str')

In [215]:
from sklearn.model_selection import train_test_split

y = mobrev['sentiment']
X = mobrev.loc[:,'Reviews']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [216]:
print("Lenght of Train" ,len(X_train))
print("Length of Test"  ,len(X_test))

Lenght of Train 1003
Length of Test 251


In [217]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1003,)
(251,)
(1003,)
(251,)


In [218]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(min_df=10,ngram_range=(1, 3))
X_train_tf=vectorizer.fit_transform(X_train).toarray()
X_test_tf=vectorizer.transform(X_test).toarray()
print(X_train_tf.shape)
print(X_test_tf.shape)

(1003, 289)
(251, 289)


In [219]:
# from sklearn.decomposition import TruncatedSVD
# svd = TruncatedSVD(n_components=280, n_iter=10, random_state=42)
# X_train_tf_svd = svd.fit_transform(X_train_tf)
# print(svd.explained_variance_ratio_.sum())
# X_test_tf_svd = svd.transform(X_test_tf)

In [220]:
y[:5]

0    POS 
1    INFO
2    POS 
3    NEG 
4    POS 
Name: sentiment, dtype: object

In [221]:
target = pd.DataFrame({"Act":y_train,"Pred":train_nb_preds})

In [222]:
target.shape

(1003, 2)

In [223]:
target.reset_index(drop=True, inplace=True)
# X_train_tf.reset_index(drop=True, inplace=True)

In [198]:
temp = pd.concat([target,pd.DataFrame(X_train_tf)],ignore_index=True,axis=1)
temp.to_csv("analyse.csv")

In [224]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

NBclassifier = GaussianNB()
NBclassifier.fit(X_train_tf, y_train)

## Predictions
train_nb_preds = NBclassifier.predict(X_train_tf)
test_nb_preds = NBclassifier.predict(X_test_tf)

print("Train Accuracy",NBclassifier.score(X_train_tf,y_train))
print(confusion_matrix(y_train,train_nb_preds))
print(classification_report(y_train,train_nb_preds))

#print("test Accuracy",NBclassifier.score(X_test_tf,y_test))
#print(confusion_matrix(y_test,test_nb_preds))
#print(classification_report(y_test,test_nb_preds))


Train Accuracy 0.4935194416749751
[[191 256 212]
 [  0 138  25]
 [  0  15 166]]
             precision    recall  f1-score   support

       INFO       1.00      0.29      0.45       659
        NEG       0.34      0.85      0.48       163
        POS       0.41      0.92      0.57       181

avg / total       0.79      0.49      0.48      1003



In [112]:
print(classification_report(y_train,train_nb_preds))


ValueError: Mix of label input types (string and number)

In [113]:
# generate classification report
from sklearn import metrics
print(metrics.classification_report(y_test, test_nb_preds))

             precision    recall  f1-score   support

       INFO       0.82      0.23      0.36       163
        NEG       0.26      0.71      0.38        38
        POS       0.30      0.62      0.41        50

avg / total       0.63      0.38      0.37       251



In [87]:
print("test Accuracy",NBclassifier.score(X_test_tf,y_test))

test Accuracy 0.3784860557768924


In [89]:
print(confusion_matrix(y_test,test_nb_preds))

[[37 64 62]
 [ 1 27 10]
 [ 7 12 31]]


In [90]:
print(classification_report(y_test,test_nb_preds))

             precision    recall  f1-score   support

       INFO       0.82      0.23      0.36       163
        NEG       0.26      0.71      0.38        38
        POS       0.30      0.62      0.41        50

avg / total       0.63      0.38      0.37       251



In [225]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X_train_tf,y_train)

## Predictions
train_logit_preds = logit.predict(X_train_tf)
test_logit_preds = logit.predict(X_test_tf)

print("Train Accuracy",logit.score(X_train_tf,y_train))
print(confusion_matrix(y_train,train_logit_preds))




Train Accuracy 0.732801595214357
[[652   2   5]
 [140  20   3]
 [116   2  63]]


In [226]:
print(classification_report(y_train,train_logit_preds))

             precision    recall  f1-score   support

       INFO       0.72      0.99      0.83       659
        NEG       0.83      0.12      0.21       163
        POS       0.89      0.35      0.50       181

avg / total       0.77      0.73      0.67      1003



In [96]:
print("test Accuracy",logit.score(X_test_tf,y_test))
print(confusion_matrix(y_test,test_logit_preds))
print(classification_report(y_test,test_logit_preds))

test Accuracy 0.6932270916334662
[[161   0   2]
 [ 32   4   2]
 [ 41   0   9]]
             precision    recall  f1-score   support

       INFO       0.69      0.99      0.81       163
        NEG       1.00      0.11      0.19        38
        POS       0.69      0.18      0.29        50

avg / total       0.74      0.69      0.61       251



In [104]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report

NBclassifier = GaussianNB()
NBclassifier.fit(X_train_tf_svd, y_train)

## Predictions
svd_train_nb_preds = NBclassifier.predict(X_train_tf_svd)
svd_test_nb_preds = NBclassifier.predict(X_test_tf_svd)

print("Train Accuracy",NBclassifier.score(X_train_tf_svd,y_train))
print(confusion_matrix(y_train,svd_train_nb_preds))
#print(classification_report(y_train,svd_train_nb_preds))



Train Accuracy 0.7666999002991027
[[553  53  53   0]
 [ 45 101  16   0]
 [ 53  14 114   0]
 [  0   0   0   1]]


In [105]:
print("val Accuracy",NBclassifier.score(X_test_tf_svd,y_test))
print(confusion_matrix(y_test,svd_test_nb_preds))
print(classification_report(y_test,svd_test_nb_preds))


val Accuracy 0.649402390438247
[[141   7  15]
 [ 22  12   4]
 [ 36   4  10]]
             precision    recall  f1-score   support

       INFO       0.71      0.87      0.78       163
        NEG       0.52      0.32      0.39        38
        POS       0.34      0.20      0.25        50

avg / total       0.61      0.65      0.62       251



In [108]:
from sklearn.linear_model import LogisticRegression
logit = LogisticRegression()
logit.fit(X_train_tf_svd,y_train)

## Predictions
svdtrain_logit_preds = logit.predict(X_train_tf_svd)
svdtest_logit_preds = logit.predict(X_test_tf_svd)

print("Train Accuracy",logit.score(X_train_tf_svd,y_train))
print(confusion_matrix(y_train,svdtrain_logit_preds))
#print(classification_report(y_train,svdtrain_logit_preds))



Train Accuracy 0.7318045862412762
[[652   2   5   0]
 [139  20   3   0]
 [117   2  62   0]
 [  1   0   0   0]]


In [109]:
print("test Accuracy",logit.score(X_test_tf_svd,y_test))
print(confusion_matrix(y_test,svdval_logit_preds))
print(classification_report(y_test,svdtest_logit_preds))

test Accuracy 0.6932270916334662
[[161   0   2]
 [ 32   4   2]
 [ 41   0   9]]
             precision    recall  f1-score   support

       INFO       0.69      0.99      0.81       163
        NEG       1.00      0.11      0.19        38
        POS       0.69      0.18      0.29        50

avg / total       0.74      0.69      0.61       251

